"""SVG / JSON / KML output generation.

The viewBox is always "0 0 W H" of the ORIGINAL image, and every coordinate
lives on that grid - proportions, aspect ratio and relative scale are
preserved exactly.
"""
from __future__ import annotations

import json
from typing import List, Optional, Sequence, Tuple

import numpy as np

from shape2svg.lines import Polyline
from shape2svg.regions import Region

PALETTE = ["#e11d48", "#2563eb", "#059669", "#d97706", "#7c3aed", "#0891b2", "#db2777", "#65a30d"]


def _fmt(v: float) -> str:
    s = f"{v:.2f}".rstrip("0").rstrip(".")
    return s if s else "0"


def _path_d(points: np.ndarray, close: bool) -> str:
    cmds = [f"M {_fmt(points[0][0])} {_fmt(points[0][1])}"]
    cmds += [f"L {_fmt(x)} {_fmt(y)}" for x, y in points[1:]]
    if close:
        cmds.append("Z")
    return " ".join(cmds)


def region_path_d(region: Region) -> str:
    d = _path_d(region.points, close=True)
    for hole in region.holes:
        d += " " + _path_d(hole, close=True)
    return d


def build_svg(
    width: int,
    height: int,
    regions: Sequence[Region] = (),
    polylines: Sequence[Polyline] = (),
    stroke_width: float = 2.0,
    stroke: Optional[str] = None,
    fill_opacity: float = 0.12,
    color_per_shape: bool = True,
    background: Optional[str] = None,
) -> str:
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" '
        f'width="{width}" height="{height}">',
        f"  <!-- generated by shape2svg: {len(regions)} region(s), {len(polylines)} polyline(s) -->",
    ]
    if background:
        parts.append(f'  <rect width="{width}" height="{height}" fill="{background}"/>')

    for i, r in enumerate(regions):
        color = stroke or (PALETTE[i % len(PALETTE)] if color_per_shape else PALETTE[0])
        parts.append(
            f'  <path d="{region_path_d(r)}" fill="{color}" fill-opacity="{fill_opacity}" '
            f'fill-rule="evenodd" stroke="{color}" stroke-width="{stroke_width}" '
            f'stroke-linejoin="round"/>'
        )
    for i, p in enumerate(polylines):
        color = stroke or (PALETTE[i % len(PALETTE)] if color_per_shape else PALETTE[0])
        d = _path_d(p.points, close=p.closed)
        parts.append(
            f'  <path d="{d}" fill="none" stroke="{color}" stroke-width="{stroke_width}" '
            f'stroke-linecap="round" stroke-linejoin="round"/>'
        )
    parts.append("</svg>")
    return "\n".join(parts)


def build_json(width: int, height: int, mode: str, regions: Sequence[Region], polylines: Sequence[Polyline]) -> str:
    doc = {
        "image": {"width": width, "height": height},
        "mode": mode,
        "regions": [
            {
                "area_px": round(r.area, 1),
                "outer": [[round(x, 2), round(y, 2)] for x, y in r.points],
                "holes": [[[round(x, 2), round(y, 2)] for x, y in h] for h in r.holes],
            }
            for r in regions
        ],
        "polylines": [
            {
                "length_px": round(p.length, 1),
                "closed": p.closed,
                "points": [[round(x, 2), round(y, 2)] for x, y in p.points],
            }
            for p in polylines
        ],
    }
    return json.dumps(doc, indent=2)


# ---------------------------------------------------------------- geo export

GeoBounds = Tuple[float, float, float, float]  # north, west, south, east


def _px_to_lonlat(points: np.ndarray, width: int, height: int, bounds: GeoBounds) -> List[Tuple[float, float]]:
    north, west, south, east = bounds
    out = []
    for x, y in points:
        lon = west + (x / width) * (east - west)
        lat = north - (y / height) * (north - south)
        out.append((lon, lat))
    return out


def build_kml(
    width: int,
    height: int,
    bounds: GeoBounds,
    regions: Sequence[Region] = (),
    polylines: Sequence[Polyline] = (),
    name: str = "shape2svg export",
) -> str:
    """KML importable into Google My Maps (linear pixel->lat/lng mapping over
    the user-supplied bounding box of the imaged area)."""
    def coord_str(pts: np.ndarray, close: bool) -> str:
        ll = _px_to_lonlat(pts, width, height, bounds)
        if close and ll and ll[0] != ll[-1]:
            ll.append(ll[0])
        return " ".join(f"{lon:.7f},{lat:.7f},0" for lon, lat in ll)

    placemarks = []
    for i, r in enumerate(regions):
        inner = "".join(
            f"<innerBoundaryIs><LinearRing><coordinates>{coord_str(h, True)}</coordinates></LinearRing></innerBoundaryIs>"
            for h in r.holes
        )
        placemarks.append(
            f"<Placemark><name>Region {i + 1}</name><Polygon><outerBoundaryIs><LinearRing>"
            f"<coordinates>{coord_str(r.points, True)}</coordinates></LinearRing></outerBoundaryIs>"
            f"{inner}</Polygon></Placemark>"
        )
    for i, p in enumerate(polylines):
        placemarks.append(
            f"<Placemark><name>Line {i + 1}</name><LineString><tessellate>1</tessellate>"
            f"<coordinates>{coord_str(p.points, p.closed)}</coordinates></LineString></Placemark>"
        )
    body = "\n    ".join(placemarks)
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<kml xmlns="http://www.opengis.net/kml/2.2">\n'
        f"  <Document><name>{name}</name>\n    {body}\n  </Document>\n</kml>\n"
    )
